import express, { type Request, type Response } from 'express';
import cors from 'cors';
import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { actors, actions, plays, towns, type Actor } from './content.js';

type Draft = { playId:string; assignments:Record<string,'main'|'support'|'rehearse'|'rest'>; timeline:{actionId:string; actorIds:string[]; act:number; slot:number}[]; endings:number[] };
type Tour = { id:string; name:string; seed:number; status:string; townIds:string[]; stopIndex:number; funds:number; reputation:number; inspiration:number; version:number; draftVersion?:number; actors:(Actor & {level:number;xp:number;stamina:number;fatigue:number})[]; visited:string[]; clues:Record<string,string[]>; draft?:Draft; history:any[]; unlocked:string[] };
const file = join(process.cwd(), 'data.json');
let tours:Tour[] = existsSync(file) ? JSON.parse(readFileSync(file,'utf8')) : [];
for(const t of tours)if(t.draft&&t.draftVersion===undefined)t.draftVersion=t.version;
let persistTimer:ReturnType<typeof setTimeout>|undefined; const persist=(immediate=false)=>{if(persistTimer){clearTimeout(persistTimer);persistTimer=undefined}if(immediate){writeFileSync(file,JSON.stringify(tours,null,2));return}persistTimer=setTimeout(()=>{persistTimer=undefined;writeFileSync(file,JSON.stringify(tours,null,2))},120)};
const app=express(); app.use(cors()); app.use(express.json({limit:'1mb'}));
const ok=(res:any,data:any)=>res.json(data); const fail=(res:any,code:string,message:string,status=400)=>res.status(status).json({code,message});
const getTour=(req:Request,res:Response):Tour|null=>{const t=tours.find(x=>x.id===req.params.id);if(!t){fail(res,'TOUR_NOT_FOUND','存档不存在',404);return null}return t};
// 共用校验边界：所有改变巡演状态的提交都必须基于客户端持有的最新版本，否则视为陈旧提交并拒绝
const requireFresh=(t:Tour,req:Request,res:Response):boolean=>{const base=Number((req.body as any)?.baseVersion);if(!Number.isInteger(base)||base!==t.version){fail(res,'STALE_VERSION','提交基于过期的巡演状态，请刷新后重试',409);return false}return true};
// 草稿内容指纹：识别“已保存草稿”与“本地未保存修改”的差异，与字段顺序无关
const canonical=(d:Partial<Draft>)=>JSON.stringify({playId:d.playId??null,assignments:Object.fromEntries(Object.entries(d.assignments??{}).sort(([a],[b])=>a<b?-1:1)),timeline:(Array.isArray(d.timeline)?d.timeline:[]).map(e=>({actionId:e?.actionId,actorIds:[...(Array.isArray(e?.actorIds)?e.actorIds:[])].sort(),act:e?.act,slot:e?.slot})),endings:Array.isArray(d.endings)?d.endings:[]});
function town(t:Tour){return towns.find(x=>x.id===t.townIds[t.stopIndex])!}
function route(seed:number){let state=(seed>>>0)||1;const shuffled=[...towns];for(let i=shuffled.length-1;i>0;i--){state=(state*1664525+1013904223)>>>0;const j=state%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}return shuffled.slice(0,6).map(x=>x.id)}
app.get('/health/live',(_,res)=>ok(res,{ok:true}));
app.get('/api/v1/content/bootstrap',(_,res)=>ok(res,{actors,actions,plays,towns}));
app.get('/api/v1/tours',(_,res)=>ok(res,{tours:tours.map(t=>({id:t.id,name:t.name,status:t.status,stopIndex:t.stopIndex,funds:t.funds,reputation:t.reputation}))}));
app.post('/api/v1/tours',(req,res)=>{const body=req.body??{};const name=String(body.name||'未命名剧团').trim().slice(0,24)||'未命名剧团';const seed=Number.isFinite(body.seed)?Number(body.seed):Math.floor(Math.random()*1000000); const t:Tour={id:randomUUID(),name,seed,status:'INVESTIGATING',townIds:route(seed),stopIndex:0,funds:420,reputation:50,inspiration:3,version:1,actors:actors.slice(0,3).map(a=>({...a,level:1,xp:0,stamina:a.stamina,fatigue:0})),visited:[],clues:{},history:[],unlocked:[]};tours.push(t);persist();ok(res,{tour:t})});
app.get('/api/v1/tours/:id',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return; ok(res,{tour:t,town:town(t),plays,actions,towns})});
app.post('/api/v1/tours/:id/travel',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;if(!requireFresh(t,req,res))return;if(t.status!=='ROUTE_SELECTION')return fail(res,'INVALID_TOUR_STATE','当前阶段不能移动',409);const next=String(req.body?.townId||'');if(t.townIds[t.stopIndex+1]!==next)return fail(res,'INVALID_ROUTE','请选择相邻路线');const target=towns.find(x=>x.id===next)!;const cost=Math.max(12,Math.round(target.capacity/8));if(t.funds<Math.round(target.capacity/8))return fail(res,'INSUFFICIENT_RESOURCE','资金不足以抵达下一站',422);t.funds-=cost;t.stopIndex++;t.status='INVESTIGATING';t.version++;persist();ok(res,{tour:t,town:target,cost})});
app.post('/api/v1/tours/:id/investigations',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;if(!requireFresh(t,req,res))return;if(t.status==='COMPLETED')return fail(res,'INVALID_TOUR_STATE','当前阶段不能调查',409);const cur=town(t);const kind=String(req.body?.kind||'');if(!['market','tavern','shrine','rehearse'].includes(kind))return fail(res,'VALIDATION_ERROR','未知调查类型');t.clues[cur.id]=Array.from(new Set([...(t.clues[cur.id]||[]),...cur.clues.slice(0,kind==='rehearse'?0:kind==='market'?1:kind==='tavern'?2:3)]));t.status='PREPARING';t.version++;persist();ok(res,{tour:t,clues:t.clues[cur.id]})});
app.get('/api/v1/tours/:id/production',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;ok(res,{draft:t.draft||{playId:plays[0].id,assignments:Object.fromEntries(t.actors.map(a=>[a.id,'main'])),timeline:[],endings:[0,0,0]},draftVersion:t.draftVersion??null,plays,actions,actors:t.actors})});
function validate(t:Tour,d:Partial<Draft>){const errors:string[]=[];if(!d||typeof d!=='object')return {errors:['编排数据格式错误'],p:undefined};const p=plays.find(x=>x.id===d.playId);if(!p)errors.push('剧目不存在');const timeline=Array.isArray(d.timeline)?d.timeline:[];if(timeline.length===0)errors.push('至少安排一个木偶动作');const seen=new Set<string>();for(const e of timeline){if(!e||typeof e!=='object'){errors.push('动作数据格式错误');continue}const a=actions.find(x=>x.id===e.actionId);if(!a)errors.push('包含未知动作');if(!Number.isInteger(e.slot)||!Number.isInteger(e.act)||e.slot<0||e.slot>3||e.act<0||e.act>2)errors.push('动作位置超出时间轴');const ids=Array.isArray(e.actorIds)?e.actorIds:[];if(ids.length===0)errors.push('每个动作至少需要一名演员');for(const id of ids){if(!t.actors.some(actor=>actor.id===id))errors.push('包含未知演员');const occupied=`${id}-${e.act}-${e.slot+((a?.duration||1)-1)}`;if(seen.has(occupied))errors.push('同一演员存在时间冲突');seen.add(occupied)}}for(const a of t.actors){const used=timeline.filter(e=>Array.isArray(e?.actorIds)&&e.actorIds.includes(a.id)).reduce((n,e)=>n+(actions.find(x=>x.id===e.actionId)?.stamina||0),0);if(used>a.stamina+10)errors.push(`${a.name}体力不足`) }const endings=Array.isArray(d.endings)?d.endings:[];if(endings.length!==3||endings.some(x=>!Number.isInteger(x)||x<0||x>2))errors.push('结局选择不完整');return {errors,p}};
app.post('/api/v1/tours/:id/production/validate',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;const d=req.body as Draft;const r=validate(t,d);ok(res,{valid:r.errors.length===0,errors:r.errors,preview:{funds:Math.max(0,t.funds-8),inspiration:Math.max(0,t.inspiration-(Array.isArray(d?.endings)&&d.endings.length===3?1:0))}})});
app.put('/api/v1/tours/:id/production',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;if(!requireFresh(t,req,res))return;const d=req.body?.draft as Draft;const r=validate(t,d);if(r.errors.length)return fail(res,'INVALID_PRODUCTION',r.errors.join('；'),422);t.draft=d;t.status='READY';t.version++;t.draftVersion=t.version;persist();ok(res,{tour:t})});
app.post('/api/v1/tours/:id/performances',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;const key=String(req.header('Idempotency-Key')||'');const previous=key?t.history.find(x=>x.idempotencyKey===key):undefined;if(previous){ok(res,{performance:previous,tour:t,replayed:true});return}if(!requireFresh(t,req,res))return;if(t.status!=='READY'||!t.draft)return fail(res,'INVALID_TOUR_STATE','请先完成合法编排并保存',409);const body=req.body??{};if(body.draftVersion!==undefined&&Number(body.draftVersion)!==t.draftVersion)return fail(res,'STALE_DRAFT','编排版本已过期，请刷新后重试',409);if(body.draft&&canonical(body.draft)!==canonical(t.draft))return fail(res,'STALE_DRAFT','存在未保存的编排修改，请先保存再演出',409);const d=t.draft;const r=validate(t,d);if(r.errors.length)return fail(res,'INVALID_PRODUCTION',r.errors.join('；'),422);const p=r.p!,cur=town(t);const tagScore=d.timeline.reduce((s:number,e:any)=>s+(actions.find(a=>a.id===e.actionId)?.tags.some(x=>cur.mood.includes(x)||p.tags.includes(x))?5:1),0);const score=Math.max(0,Math.min(100,45+tagScore+Math.min(20,t.reputation/5)-d.timeline.length*1));const fill=Math.min(1,0.45+t.reputation/160+tagScore/250);const income=Math.round(cur.capacity*fill*cur.ticket/10);const feedback=score>=75?`${cur.audience}喜欢你对“${cur.legend}”的回应，散场后仍在讨论结尾。`:`观众希望动作更贴近${cur.mood}的气氛；有人记住了你的勇气。`;const perf={id:randomUUID(),idempotencyKey:key||undefined,townId:cur.id,score,income,feedback,ending:d.endings[2],snapshot:d,createdAt:new Date().toISOString()};t.history.push(perf);t.funds+=income;t.reputation=Math.max(0,Math.min(100,t.reputation+Math.round((score-55)/5)));t.inspiration=Math.max(0,t.inspiration+(score>72?1:0));for(const a of t.actors){a.xp+=Math.round(score/4);a.stamina=Math.max(10,a.stamina-12);a.fatigue=Math.min(3,a.fatigue+(score<50?1:0));if(a.xp>=a.level*100){a.level++;a.xp-=a.level*100}}t.visited.push(cur.id);t.status=t.stopIndex>=t.townIds.length-1?'FINALE_READY':'ROUTE_SELECTION';t.draft=undefined;t.draftVersion=undefined;t.version++;persist(true);ok(res,{performance:perf,tour:t})});
app.post('/api/v1/tours/:id/rest',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;if(!requireFresh(t,req,res))return;for(const a of t.actors)a.stamina=Math.min(100,a.stamina+25),a.fatigue=Math.max(0,a.fatigue-1);t.version++;persist();ok(res,{tour:t})});
app.get('/api/v1/tours/:id/history',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;ok(res,{history:t.history})});
app.post('/api/v1/tours/:id/finale',(req,res)=>{const t=getTour(req,res);if(!t||!('id'in t))return;if(!requireFresh(t,req,res))return;if(t.status!=='FINALE_READY')return fail(res,'INVALID_TOUR_STATE','终局尚未开放',409);const avg=t.history.slice(1).reduce((n,x)=>n+x.score,0)/Math.max(1,t.history.length-1);t.status='COMPLETED';t.version++;persist();ok(res,{ending:avg>=75?'万镇喝彩':avg>=55?'忠于舞台':'散场之后',average:Math.round(avg),tour:t})});
app.use(express.static(join(process.cwd(),'dist-web')));
app.listen(3001,()=>console.log('API listening on http://localhost:3001'));
